### ISSUE TITLE
gollum-rails  to join gollum organisation

### ISSUE THREAD

**Issue by dancinglightning** [gollum/gollum-lib#132]
I would have written to a person (since it's not really an issue of gollum-lib) but don't know to whom.
So i'm using this as a sort of message board, sorry.

Florian (nirnanaaa) has what seems the most "live" [gollum rails](https://github.com/nirnanaaa/gollum_rails). It is more like a library though.
He also has a [gollum_redmine](https://github.com/nirnanaaa/gollum_redmine) though, that off course being redmine focused.

Together we were going to make his gollum_rails a "modern" rails engine by folding some of the redmine code and writing new engine related stuff.

Now it looks like gollum-lib is in the process of extracting the backend of gollum, and gollum will be "just"
a sinatra front end.

So i was wondering, since we are doing this rails front-end, it could be under the gollum organization.
Since organizations have good access control, we could be restricted to the rails part for starters.
But since we'd all be working on similar things, joining the organization would make sense to me.

Torsten

**Comment by dometto** [comment]
Interesting proposal. :)

Can you be a bit more specific on what you're planning to do? If you want to develop a full-fledged rails webapp, I'd be worried a bit that we'd be developing the same app twice (which you're of course welcome to do, but doing would not really be a goal of the gollum project). If the plan is rather to develop an 'engine'/rack servlet for easy rails integration, I can see the need for that, and that would potentially be a nice contribution to the gollum ecosystem.

Plus, I would certainly welcome some more people looking at gollum-related code. :) What do you think, @sunny @jamieoliver @bartkamphorst?

**Comment by dancinglightning** [comment]
The second: the idea is to develop a rails engine, an easy drop in into an existing rails application.
not sure how to be more specific, using rails assets/stylesheets/templates. The engine would be mounted and all those things could be changed and off course it would run in the main apps layout.

**Comment by sunny** [comment]
I'm all for it. I think it will help both the project and Gollum to pull it under the organisation.

> Now it looks like gollum-lib is in the process of extracting the backend of gollum, and gollum will be "just"
> a sinatra front end.

It's doing that already… or at least it should be. Right now we are even extracting the Git adapter out of gollum-lib.

**Comment by dancinglightning** [comment]
Great, and for that kind of "extraction" it certainly heps to have two "users" of the lib.

btw: i did an initial spurt and got a working prototype that starts (embedded in a test app) and shows some of the views. So it's looking good.

**Comment by dometto** [comment]
@dancinglightning, what should the new repository be called? :)

**Comment by dancinglightning** [comment]
@dometto i think gollum_rails would be best: we are building on that code, so the name should stay.

**Comment by bartkamphorst** [comment]
> i did an initial spurt and got a working prototype that starts (embedded in a test app) and shows some of the views.

Nice. :+1: 

> i think gollum_rails would be best

Would @nirnanaaa want the repo to change ownership completely then?

**Comment by dancinglightning** [comment]
@bartkamphorst No, @nirnanaaa should be committer too, and will stay owner of the gem.
He is on board and we are in contact, he's just a bit busy and i'm a bit eager ( i have a site where i want to use this)

**Comment by nirnanaaa** [comment]
Hey, I think it would be best to take my ideas and transfer them into a clean, more elegant way. 

GollumRails is missing some functionality as @dancinglightning mentioned, which must be included (Override Settings, more convenient Rails behavior https://github.com/nirnanaaa/gollum_rails/issues/26). 

Would it be best to transfer gollum_rails as it is to gollum or should we rewrite it from scratch on top of gollum_rails and gollum_redmine?

I could take a part in development if wanted, though.

@dancinglightning @bartkamphorst @dometto

**Comment by dometto** [comment]
I've created https://github.com/gollum/gollum_rails and @nirnanaaa and @dancinglightning have commit (and admin) access to that repo. I leave it to you guys to decide whether to push existing code as an initial commit of to start over fresh. Welcome to the org, looking forward to seeing this project grow!

**Comment by nirnanaaa** [comment]
Thanks a lot. Will communicate with @dancinglightning about your points.

**Comment by dancinglightning** [comment]
OK! cool, thanks for the invite guys!

@nirnanaaa , i'll create an issue on the new repo.

**Comment by nirnanaaa** [comment]
@dancinglightning just emailing you, too

**Comment by sunny** [comment]
Welcome to the team! :sparkles:

**Comment by gerwitz** [comment]
This project seems to have gone missing. Meanwhile, I have implemented a very rough Rails engine that provides a wiki based on gollum-lib. It is **not** a Rails version of Gollum, as it purposefully lacks most of Gollum's features. I built it as a minor component of a growing intranet project.

If anyone's has a similar need and is interested in starter code that has no tests and is likely riddled with bugs, I would be happy to share.

**Comment by dancinglightning** [comment]
Hi @gerwitz, 
the project was removed from the organisation because communication broke down and in the end it is their organisation.
But it still exists, and is functional in as much as all tests work.
The funny situation is that i have no need for it and off course the toolbox is broken so i don't know where to advertise it's existence.

Shame you had to redo, maybe you can have a look at what i did anyway https://github.com/dancinglightning/gollum_rails

It also is not a gullum (feature) clone.

**Comment by gerwitz** [comment]
No worries, I also found https://github.com/nirnanaaa/gollum_rails but we wanted a hierarchical wiki structure so would have had to modify heavily anyway. It sure would have been nice to have found your engine first, though!

If anyone else happens upon this closed issue and cares, we're sharing our (very ugly) source here: https://github.com/TheArtificial/rails-wiki

**Comment by fkasper** [comment]
Hey @gerwitz my old gollum implementation has a hierarchical wiki structure! You can lookup your code there

**Comment by nirnanaaa** [comment]
@fkasper @gerwitz crap wrong account. Just want to post how I see this - My opinion. I do think it is easier to adapt the gollum-lib way on your project, as it is a very well tested and major software. No matter if you use gollum_rails underneath it or decide to write your own rails engine. It has some handy abstractions and takes care of a lot of things you will run into. My point is you don't have to start a git implementation based on rugged from scratch. Based on gollum-lib you have everything you need in a friction of the time you would otherwise spend on searching for indexing or some other methods.

**Comment by gerwitz** [comment]
Unfortunately, I've already written my own engine, and am already using it in (internal) production. Using gollum-lib, but it feels like only a fraction of it, which smells wasteful.

If I'd seen gollum_rails I would have used it instead of rolling my own model abstraction! Since your project is alive again, I ought to revisit and see if refactoring using it makes sense.
